### ISSUE TITLE
Custom step color

### ISSUE THREAD

**Issue by leobia** [guastallaigor/vue-horizontal-timeline#76]
Hi,

is there a possibility that you implement a prop to customize the color of the steps?

![image](https://user-images.githubusercontent.com/26444579/121206616-e8a9b980-c878-11eb-925d-f6639839a965.png)

I could not find it on the doc or source code, as a workaround I am overwriting this css:

```css
.vue-horizontal-timeline .timeline ol li.add-step[data-v-c0e978a0]:not(:last-child)::after {
  background: black !important;
}
```

Btw great work!
